language: go

go:
   - 1.6
   - 1.7.x
   - master
    
before_install:
   - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

sudo: false

before_script:
  - go vet ./...

install:
   # Add Godeps dependencies to GOPATH and PATH
   - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
   - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
